from flask import Flask, request, jsonify
import pyotp
import time
import os
import json

app = Flask(__name__)

base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB_FILE = os.path.join(base_dir, 'data', 'mfa_db.json')

def load_db():
    if os.path.exists(DB_FILE):
        try:
            with open(DB_FILE, 'r') as f:
                return json.load(f)
        except (json.JSONDecodeError, ValueError):
            return {}
    return {}

def save_db(db):
    with open(DB_FILE, 'w') as f:
        json.dump(db, f, indent=4)

users_db = load_db()

@app.route('/')
def index():
    return "VaultGuard MFA Server is Running (Secure)"

@app.route('/register', methods=['POST'])
def register():
    data = request.json
    username = data.get('username')
    
    if not username:
        return jsonify({"error": "Username required"}), 400
        
    if username in users_db:
        return jsonify({"error": "User already exists"}), 409
        
    # Generate TOTP Secret for this user
    secret = pyotp.random_base32()
    users_db[username] = {"secret": secret}
    save_db(users_db)
    
    print(f"[Server] Registered user '{username}' with secret: {secret}")
    
    return jsonify({
        "message": "Registration successful", 
        "secret": secret,
        "info": "Secret will be used to generate OTPs for dual transfer to mobile and vault apps"
    })

@app.route('/login', methods=['POST'])
def login():
    data = request.json
    username = data.get('username')
    otp_code = data.get('otp')
    
    if not username or not otp_code:
        return jsonify({"error": "Missing credentials"}), 400
        
    user = users_db.get(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
        
    secret = user['secret']
    totp = pyotp.TOTP(secret, interval=60)  # 60-second interval as per requirements
    
    # Verify (window=1 means allow +/- 60 seconds for clock drift)
    if totp.verify(otp_code, valid_window=1):
        return jsonify({"message": "Access Granted", "authenticated": True})
    else:
        return jsonify({"message": "Invalid OTP", "authenticated": False}), 401

@app.route('/get-otp', methods=['GET'])
def get_otp():
    """
    Dual Transfer Mechanism: Both Mobile App and VaultGuard can request current OTP.
    The server generates the OTP using TOTP (Time-based), ensuring both get the same code.
    This simulates the "simultaneous transfer" requirement - both apps fetch from same source.
    
    In production, this could be push notifications, but polling works for demonstration.
    """
    username = request.args.get('username')
    
    if not username:
        return jsonify({"error": "Username required"}), 400
    
    user = users_db.get(username)
    if not user:
        return jsonify({"error": "User not found"}), 404
        
    secret = user['secret']
    totp = pyotp.TOTP(secret, interval=60)  # 60-second interval
    current_otp = totp.now()
    time_remaining = int(totp.interval - (time.time() % totp.interval))
    
    print(f"[Server] Generated OTP {current_otp} for user '{username}' (valid for {time_remaining}s)")
    
    return jsonify({
        "otp": current_otp,
        "time_remaining": time_remaining,
        "username": username,
        "message": "OTP generated by server for dual transfer to both mobile and vault apps"
    })

@app.route('/get-otp-simulation', methods=['GET'])
def get_otp_simulation():
    """
    Deprecated: Use /get-otp instead for dual transfer mechanism.
    Kept for backwards compatibility.
    """
    return get_otp()

if __name__ == '__main__':
    # SSL Context 'adhoc' generates a self-signed cert on the fly
    print("Starting MFA Server on port 5000 (HTTPS)...")
    try:
        app.run(host='0.0.0.0', port=5000, ssl_context='adhoc', debug=True)
    except Exception as e:
        print(f"Failed to start with SSL: {e}. Fallback to HTTP for debugging (NOT SECURE).")
        app.run(host='0.0.0.0', port=5000, debug=True)
